### check admin
get http://localhost:5000/admin-api/test-admin


###user creation
post http://localhost:5000/user-api/user
Content-Type: application/json

{
    "userType":"user",
    "username":"rikhil",
    "password":"12345",
    "email":"jrr@mail.com"
}


#### user login
post http://localhost:5000/user-api/login
Content-Type: application/json

{
    "userType":"user",
    "username":"rikhil",
    "password":"12345"
   
}
